### ISSUE TITLE
Add Comonent Typing

### ISSUE THREAD

**Issue by lecoqjacob** [slavfox/snecs#6]
Can seem to figure out the issue on this one:

<img width="1062" alt="CleanShot 2022-06-24 at 15 05 36@2x" src="https://user-images.githubusercontent.com/9278174/175659911-9fcc24f9-6c23-4c87-98e9-84a11ccd3a4d.png">

Seems the mypy typings are off

**Comment by slavfox** [comment]
`add_component` expects a component *instance*, you're trying to add the entire type.

```python
# wrong, the type of `Position` is `type`, which is not a subtype of `Component`
add_component(id, Position)

# correct, the type of `Position(0, 0)` is `Position`, which is a subtype of `Component`
add_component(id, Position(0, 0))
```

**Comment by lecoqjacob** [comment]
Man i feel dumb. Whoops. Apologies

**Comment by lecoqjacob** [comment]
Have you found a good way for the Component Type to be referenced in the Query themselves?

**Comment by slavfox** [comment]
Could you elaborate on that? 

If you mean having the return type of queries be inferred, I tried, but unfortunately Mypy doesn't support variadic generics. *Perhaps* `ParamSpec` in 3.10 might be of help here, but I haven't looked at it yet because I don't want to break compatibility with PyPy -- although, I suppose, I might add a conditional dependency on `typing_extensions` which backports `ParamSpec` for versions older than 3.10.

**Comment by lecoqjacob** [comment]
Yes that is what I was referring too. I am new to python (coming from typescript / rust) so I don't know a good way for type-casting here.

<img width="742" alt="CleanShot 2022-06-24 at 15 28 26@2x" src="https://user-images.githubusercontent.com/9278174/175662659-26dd6592-be98-4e41-b9f2-2203850fb966.png">

This compiles and is correct, but mypy complains that it doesn't know the specific type

**Comment by slavfox** [comment]
Without having mypy in front of me, I *think* an explicit type annotation will take care of that:
```python
p: Position
r: Renderable
for entity_id, (p, r) in snecs.Query([Position, Renderable]):
   ...
```

If that doesn't work, you need [`typing.cast()`](https://docs.python.org/3/library/typing.html#typing.cast): 
```python
for entity_id, (p, r) in snecs.Query([Position, Renderable]):
    print(entity_id, cast(Position, p).x, r)
```


As a sidenote, `.compile()` is intended to be used outside of the hot part of the code, you'd use it like this:

```python
RENDERABLE_QUERY = snecs.Query((Position, Renderable)).compile()

def main(...):
    ...
    for entity_id, (p, r) in RENDERABLE_QUERY:
        ...
```

**Comment by slavfox** [comment]
By the way, if that last example seems unintuitive, queries implement the iterator protocol -- coming from Rust, you can think of that as:
```rust
let renderable_query = Query::new(vec![Position, Renderable]).compile();

fn main() {
    for (entity_id, (p, r)) in renderable_query.iter() {
        ...
    }
}
```

Python's `for` statement calls the `__iter__()` magic method, which is just an implicit equivalent to Rust's *explicit* `.iter()`. `for ... in query` creates a new iterator (therefore running the query anew) every time, it's not iterating over the same results, even though it may seem so at first glance :)

**Comment by lecoqjacob** [comment]
Ah that `cast` method is exactly what I need. I kept trying to use casting in rust with `as Position`

**Comment by lecoqjacob** [comment]
Super helpful. Thanks for the quick feedback!

**Comment by slavfox** [comment]
If you're in the roguelike Discord, feel free to ping me there any time and I'll be happy to help you out with any issues you might have!
